[[item]]
code = "a"
desc = "ls current directory"
cmd = "ls -a"

[[item]]
code = "b"
desc = "See what is in run.toml"
cmd = "cat ./run.toml"

[[item]]
code = "c"
desc = "See cargo help"
cmd = "cargo -h"